### ISSUE TITLE
Tạo dữ liệu mẫu cho blog, sản phẩm

### ISSUE THREAD

**Issue by thaihuy2001** [thaihuy2001/DO_AN_CNPM#26]

**Comment by thaihuy2001** [comment]
![image](https://user-images.githubusercontent.com/115332985/230528722-4db61f1f-5d02-498f-a056-b21b8deccfcb.png)

**Comment by chuvanloi** [comment]
![image](https://user-images.githubusercontent.com/114088901/230528814-5dbdd201-3142-4c02-8647-b008ad175a60.png)
![image](https://user-images.githubusercontent.com/114088901/230528992-696c911b-0bfd-4ad9-a98a-7450f3ede5da.png)
