### ISSUE TITLE
Lập trình thêm sửa xoá sản phẩm

### ISSUE THREAD

**Issue by thaihuy2001** [thaihuy2001/DO_AN_CNPM#28]

**Comment by chuvanloi** [comment]
![image](https://user-images.githubusercontent.com/114088901/229956478-ddb49d15-1c74-4534-9a7c-9fc56cde2dfc.png)

**Comment by chuvanloi** [comment]
![image](https://user-images.githubusercontent.com/114088901/229956628-887bf073-ebc6-4635-999b-9077c2a57687.png)
![image](https://user-images.githubusercontent.com/114088901/229956763-51e7d98b-98b4-4a34-8e19-72fde9747b52.png)
