### ISSUE TITLE
Lập trình lấy dữ liệu sản phẩm lên trang chủ

### ISSUE THREAD

**Issue by thaihuy2001** [thaihuy2001/DO_AN_CNPM#29]

**Comment by chuvanloi** [comment]
![image](https://user-images.githubusercontent.com/114088901/230528061-d84e5b3f-3510-402e-b775-516cdd2be165.png)
![image](https://user-images.githubusercontent.com/114088901/230528128-74883ca4-1404-4006-bd68-659d7b7ea761.png)
![image](https://user-images.githubusercontent.com/114088901/230528205-d0df9acf-7627-43bb-9a92-d7685b33201a.png)
![image](https://user-images.githubusercontent.com/114088901/230528375-0d5f0bb0-5c5d-44be-898b-c4afe472bfa7.png)
