### ISSUE TITLE
Lập trình lấy dữ liệu blog lên trang chủ

### ISSUE THREAD

**Issue by chuvanloi** [thaihuy2001/DO_AN_CNPM#32]

**Comment by thaihuy2001** [comment]
![image](https://user-images.githubusercontent.com/115332985/230528493-dba79bfb-038e-4b7c-abcb-968f1796573b.png)
![image](https://user-images.githubusercontent.com/115332985/230528523-54686acc-fd13-49ef-9ddd-5b9d6e40f13c.png)
![image](https://user-images.githubusercontent.com/115332985/230528558-240a4ad8-6dfc-4d58-9deb-0cb37baa6758.png)
